name: Renovate Checkbox

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write

jobs:
  tick:
    runs-on: ubuntu-latest
    steps:
      - uses: Jolg42/action-renovate-checkbox@v1
        with:
          master-issue-id: ${{ vars.renovate_issue_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
