name: Renovate Checkbox

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write

jobs:
  tick:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}

      - uses: Jolg42/action-renovate-checkbox@v1
        with:
          master-issue-id: ${{ vars.renovate_issue_id }}
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
