name: Renovate Checkbox

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write

jobs:
  tick:
    runs-on: ubuntu-latest
    steps:
      - if: vars.use_custom_token != 'true'
        uses: Jolg42/action-renovate-checkbox@v1
        with:
          master-issue-id: ${{ vars.renovate_issue_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - id: get_token
        if: vars.use_custom_token == 'true'
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}

      - if: vars.use_custom_token == 'true'
        uses: Jolg42/action-renovate-checkbox@v1
        with:
          master-issue-id: ${{ vars.renovate_issue_id }}
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
